name: Test PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  test-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: |
        go get
        go test